run:
  deadline: 5m
  allow-parallel-runners: true

issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - dupl
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
