//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVM) DeepCopyInto(out *SmolVM) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVM.
func (in *SmolVM) DeepCopy() *SmolVM {
	if in == nil {
		return nil
	}
	out := new(SmolVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmolVM) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVMList) DeepCopyInto(out *SmolVMList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SmolVM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVMList.
func (in *SmolVMList) DeepCopy() *SmolVMList {
	if in == nil {
		return nil
	}
	out := new(SmolVMList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmolVMList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVMNetwork) DeepCopyInto(out *SmolVMNetwork) {
	*out = *in
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]SmolVMPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVMNetwork.
func (in *SmolVMNetwork) DeepCopy() *SmolVMNetwork {
	if in == nil {
		return nil
	}
	out := new(SmolVMNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVMPort) DeepCopyInto(out *SmolVMPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVMPort.
func (in *SmolVMPort) DeepCopy() *SmolVMPort {
	if in == nil {
		return nil
	}
	out := new(SmolVMPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVMResources) DeepCopyInto(out *SmolVMResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVMResources.
func (in *SmolVMResources) DeepCopy() *SmolVMResources {
	if in == nil {
		return nil
	}
	out := new(SmolVMResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVMSpec) DeepCopyInto(out *SmolVMSpec) {
	*out = *in
	out.Resources = in.Resources
	out.Storage = in.Storage
	in.Network.DeepCopyInto(&out.Network)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVMSpec.
func (in *SmolVMSpec) DeepCopy() *SmolVMSpec {
	if in == nil {
		return nil
	}
	out := new(SmolVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVMStatus) DeepCopyInto(out *SmolVMStatus) {
	*out = *in
	if in.RuntimePID != nil {
		in, out := &in.RuntimePID, &out.RuntimePID
		*out = new(int32)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]SmolVMPort, len(*in))
		copy(*out, *in)
	}
	if in.StorageGiB != nil {
		in, out := &in.StorageGiB, &out.StorageGiB
		*out = new(int64)
		**out = **in
	}
	if in.OverlayGiB != nil {
		in, out := &in.OverlayGiB, &out.OverlayGiB
		*out = new(int64)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVMStatus.
func (in *SmolVMStatus) DeepCopy() *SmolVMStatus {
	if in == nil {
		return nil
	}
	out := new(SmolVMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmolVMStorage) DeepCopyInto(out *SmolVMStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmolVMStorage.
func (in *SmolVMStorage) DeepCopy() *SmolVMStorage {
	if in == nil {
		return nil
	}
	out := new(SmolVMStorage)
	in.DeepCopyInto(out)
	return out
}
